#pragma once

// clang-format off
#if defined(_MSC_VER)
// NOTE: Visual C++
#define ANEMONE_MSVC_SUPPRESS_WARNING(w) __pragma(warning(disable : w))

#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_BEGIN \
    __pragma(warning(push)) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4265) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4365) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4514) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4668) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4710) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4711) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4820) \
    ANEMONE_MSVC_SUPPRESS_WARNING(4986) \
    ANEMONE_MSVC_SUPPRESS_WARNING(5039) \
    ANEMONE_MSVC_SUPPRESS_WARNING(5204) \
    ANEMONE_MSVC_SUPPRESS_WARNING(5219) \
    ANEMONE_MSVC_SUPPRESS_WARNING(5220)

#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_END \
    __pragma(warning(pop))

#elif defined(__clang__)
// NOTE: Clang
#define ANEMONE_CLANG_PRAGMA_TO_STR(x) _Pragma(#x)
#define ANEMONE_CLANG_SUPPRESS_WARNING(w) ANEMONE_CLANG_PRAGMA_TO_STR(clang diagnostic ignored w)

#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_BEGIN \
    _Pragma("clang diagnostic push") \
    ANEMONE_CLANG_SUPPRESS_WARNING("-Wpadded") \
    ANEMONE_CLANG_SUPPRESS_WARNING("-Wweak-vtables") \
    ANEMONE_CLANG_SUPPRESS_WARNING("-Wreserved-id-macro")

#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_END \
    _Pragma("clang diagnostic pop")

#elif defined(__GNUC__)
// NOTE: GCC
#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_BEGIN
#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_END
#else
#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_BEGIN
#define ANEMONE_SUPPRESS_WARNINGS_GENERATED_BY_STD_HEADERS_END
#endif
// clang-format on
